/**
 * Created by Hajay on 2018/2/2.
 */

var en = {
    1001: 'BitUP Candy Delivery',
    1002: 'Join the Bitup telegram group',
    1003: 'Enter your ETH wallet address',
    1004: 'Enter picture verification code',
    1005: 'Generate your special invitation link',
    1006: 'Activity detailed rules',
    1007: 'BitUP platform will issue BUT (BitUP Token), an ERC20-compatible crypto token implemented on the public Ethereum blockchain. BUT will be issued to token sale participants as the certificate to receive proportional rights and interests, including all assets and liabilities. BUT will also be widely used in the BitUP platform ecosystem as the main payment method. BUT will be publicly tradable on exchange platforms, and token sale participants can trade the tokens according to their needs.',
    1008: 'Join the telegram group',
    1009: 'Download Telegram',
    1010: 'White Paper',
    //1011: 'Your special invitation link',
    //1012: 'Copy',
    1011: 'Invited',
    1012: 'Earned',
    1013: 'Join the BitUP telegram group.',
    1014: 'Send the following verification number to the group to get 10 BUT.',
    1015: 'copy',
    1016: 'Share your link to your friends, each successful recommendation to join this activity can get 5 BUT.',
    1017: 'BitUP reserves the rights to the final explanation of activity.',
    1018: 'Close',
    1019: 'Please enter the correct ETH wallet address!',
    1020: '简体中文',
    1021: 'Activity detailed rules',
    1022: 'Join the BitUP telegram group.',
    1023: 'Send the following verification number to the group to get 10 BUT.',
    1024: 'Share your link to your friends, each successful recommendation to join this activity can get 5 BUT.',
    1025: 'BitUP reserves the rights to the final explanation of activity.',
    1026: "The next candy event will be started soon, and the criteria for delivering reward is 'reward > 30BUT'. The reward will be deliveried before Feb 28th.  Guys who don't meet the criteria, plz invite more friends in the next candy event. Thanks again for your participation!",
    1027: "Get your BUT candy",
    1028: "The criteria for delivering reward is 'reward > 30BUT'.",
    1029: 'The BitUP Candy Event has ended. Thanks for your participation! You can input your ETH address and check your reward of BitUP candy. The reward will be delivered before Feb 28th. Note: only participants meeting our criteria will get rewarded. ',
    1030: 'Check Your Candy'
};

var cn = {
    1001: 'BitUP糖果派送活动',
    1002: '加入BitUP官方Telegram群',
    1003: '输入您的以太坊钱包地址',
    1004: '输入图片验证码',
    1005: '获取您的分享链接',
    1006: '活动详细规则',
    1007: 'BitUP平台发行的数字货币名称为 BUT (BitUP Token)，它基于以太坊技术，将作为兑换人的凭证，享受兑换比例相对应的权益，包括所有资产与负债等。BUT也将作为平台主要支付工具，在BitUP平台的生态系统中使用。BUT将会在各大交易所挂牌，兑换人可根据自己的实际需求在交易所进行流通。',
    1008: '加入电报群',
    1009: '下载Telegram',
    1010: '白皮书介绍',
    1011: '已邀请人数(人次)',
    1012: '已获取BUT(个数)',
    1013: '加入BitUP官方Telegram群',
    1014: '发送您的个人识别码至Telegram群，获取10个BUT奖励。',
    1015: '复制',
    1016: '分享您的链接给朋友，每邀请一位朋友参加活动即可获得5个BUT奖励。',
    1017: '注：最终解释权归BitUP所有。',
    1018: '关闭',
    1019: '请输入正确的以太坊钱包地址！',
    1020: 'English',
    1021: '活动详细规则',
    1022: '加入BitUP官方Telegram群。',
    1023: '发送您的个人识别码至Telegram群，获取10个BUT奖励。',
    1024: '分享您的链接给朋友，每邀请一位朋友参加活动即可获得5个BUT奖励。',
    1025: '注：最终解释权归BitUP所有。',
    1026: "下一轮糖果活动会在近期开启，整个糖果活动发放奖励标准是累积奖励大于30BUT,  并在二月底之前发放。 没有满足发放奖励条件的同学请在下一轮邀请更多伙伴入群获得更多糖果，再次感谢大家的踊跃参与！",
    1027: "获取您的BUT糖果",
    1028: "糖果发放奖励标准为30BUT以上",
    1029: 'BitUP糖果派送活动已结束。感谢您的参与！您可以输入ETH地址查看奖励情况。糖果奖励将于2月28日前发放。注：只有符合活动规则的参与者才会获得奖励。',
    1030: '查看活动奖励'
};